services:

  - type: web
    name: happinama-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: JUDGE0_URL
        value: https://YOUR_JUDGE0_SERVICE_NAME.onrender.com

  - type: web
    name: happinama-judge0
    runtime: docker
    dockerfilePath: ./judge0.dockerfile
    rootDir: backend
    envVars:
      - key: REDIS_URL
        value: redis://localhost:6379
